### ISSUE TITLE
Issue with Missing Argument and KeyError during Experiment Reproduction

### ISSUE THREAD

**Issue by louislee711** [RenqiChen/Genomic-Selection#3]
Hello,

I have read your paper and found it fascinating. I would like to try reproducing your experiments, but I encountered some issues while running the code.

Missing Argument:
Based on my observation, it seems that the script is missing the argument if args.__contains__("fam_path").
Could you confirm if there are any missing files or parameters that I need to include? Below is the error message I received:

```
bash distributed_train_rice3k.sh
[2024-09-28 03:53:56,257] torch.distributed.run: [WARNING] 
[2024-09-28 03:53:56,257] torch.distributed.run: [WARNING] *****************************************
[2024-09-28 03:53:56,257] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-09-28 03:53:56,257] torch.distributed.run: [WARNING] *****************************************
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
18081808

453
453dataset finished

dataset finished
loader finished
loader finished
/usr/local/lib/python3.10/dist-packages/apex/__init__.py:68: DeprecatedFeatureWarning: apex.amp is deprecated and will be removed by the end of February 2023. Use [PyTorch AMP](https://pytorch.org/docs/stable/amp.html)
  warnings.warn(msg, DeprecatedFeatureWarning)
/usr/local/lib/python3.10/dist-packages/apex/__init__.py:68: DeprecatedFeatureWarning: apex.amp is deprecated and will be removed by the end of February 2023. Use [PyTorch AMP](https://pytorch.org/docs/stable/amp.html)
  warnings.warn(msg, DeprecatedFeatureWarning)
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : TrueSelected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.


Defaults for this optimization level are:opt_level              : O1

cast_model_type        : Noneenabled                : True

opt_level              : O1patch_torch_functions  : True

cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : Nonekeep_batchnorm_fp32    : None

master_weights         : Nonemaster_weights         : None

loss_scale             : dynamic
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...Processing user overrides (additional kwargs that are not None)...

After processing overrides, optimization options are:After processing overrides, optimization options are:

enabled                : Trueenabled                : True

opt_level              : O1opt_level              : O1

cast_model_type        : Nonecast_model_type        : None

patch_torch_functions  : Truepatch_torch_functions  : True

keep_batchnorm_fp32    : Nonekeep_batchnorm_fp32    : None

master_weights         : Nonemaster_weights         : None

loss_scale             : dynamicloss_scale             : dynamic

/usr/local/lib/python3.10/dist-packages/apex/amp/_process_optimizer.py:344: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /opt/pytorch/pytorch/torch/csrc/tensor/python_tensor.cpp:83.)
  optimizer._amp_stash.dummy_overflow_buf = torch.cuda.IntTensor([0]);
/usr/local/lib/python3.10/dist-packages/apex/amp/_process_optimizer.py:344: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /opt/pytorch/pytorch/torch/csrc/tensor/python_tensor.cpp:83.)
  optimizer._amp_stash.dummy_overflow_buf = torch.cuda.IntTensor([0]);
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboardX/record_writer.py", line 47, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: 'logs/2024928_rice3k.pth_4_100_cuda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/GS/main_rice3k.py", line 170, in <module>
    main()
  File "/mnt/data/GS/main_rice3k.py", line 166, in main
    normal_train_test(train_loader, test_loader, model, optimizer, criterion, args)
  File "/mnt/data/GS/main_rice3k.py", line 111, in normal_train_test
  0%|                                                                                                                              | 0/100 [00:00<?, ?it/s]start epoch [1/100]
    writer = SummaryWriter(name)
  File "/usr/local/lib/python3.10/dist-packages/tensorboardX/writer.py", line 300, in __init__
    self._get_file_writer()
  File "/usr/local/lib/python3.10/dist-packages/tensorboardX/writer.py", line 348, in _get_file_writer
    self.file_writer = FileWriter(logdir=self.logdir,
  File "/usr/local/lib/python3.10/dist-packages/tensorboardX/writer.py", line 104, in __init__
    self.event_writer = EventFileWriter(
  File "/usr/local/lib/python3.10/dist-packages/tensorboardX/event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "/usr/local/lib/python3.10/dist-packages/tensorboardX/record_writer.py", line 51, in directory_check
    os.makedirs(path)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'logs/2024928_rice3k.pth_4_100_cuda:0'
  0%|                                                                                                                              | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/data/GS/main_rice3k.py", line 170, in <module>
    main()
  File "/mnt/data/GS/main_rice3k.py", line 166, in main
    normal_train_test(train_loader, test_loader, model, optimizer, criterion, args)
  File "/mnt/data/GS/main_rice3k.py", line 118, in normal_train_test
    train_loss = train_one_epoch(i, train_loader, model, criterion, optimizer, args)
  File "/mnt/data/GS/main_rice3k.py", line 25, in train_one_epoch
    for step, data in enumerate(loader):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 705, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/data/GS/dataset_rise3k_45.py", line 198, in __getitem__
    label = (label - self.args.data_mean) / self.args.data_std
AttributeError: 'Namespace' object has no attribute 'data_mean'

[2024-09-28 03:54:01,266] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 22508 closing signal SIGTERM
[2024-09-28 03:54:01,329] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 22507) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main_rice3k.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-28_03:54:01
  host      : 64ccdd38f67e
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 22507)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

2. Attempted Fix and New Error:
I tried adding the necessary arguments, but this led to a new error:

```
bash distributed_train_rice3k.sh
[2024-10-02 08:58:25,686] torch.distributed.run: [WARNING] 
[2024-10-02 08:58:25,686] torch.distributed.run: [WARNING] *****************************************
[2024-10-02 08:58:25,686] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-10-02 08:58:25,686] torch.distributed.run: [WARNING] *****************************************
./configs/rice3k.apco_rev_repro.json
./configs/rice3k.apco_rev_repro.json
normalize: True
normalize: True
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
Traceback (most recent call last):
  File "/mnt/data/GS/main_rice3k.py", line 175, in <module>
Traceback (most recent call last):
  File "/mnt/data/GS/main_rice3k.py", line 175, in <module>
    main()
  File "/mnt/data/GS/main_rice3k.py", line 146, in main
    main()
  File "/mnt/data/GS/main_rice3k.py", line 146, in main
    train_dataset, test_dataset = fetch_dataset(args)
  File "/mnt/data/GS/dataset_rise3k_45.py", line 52, in fetch_dataset
    train_dataset, test_dataset = fetch_dataset(args)
  File "/mnt/data/GS/dataset_rise3k_45.py", line 52, in fetch_dataset
    train_d, test_d = split_dataset(data_root, fam_path, which_k)
  File "/mnt/data/GS/dataset_rise3k_45.py", line 150, in split_dataset
    train_d, test_d = split_dataset(data_root, fam_path, which_k)
  File "/mnt/data/GS/dataset_rise3k_45.py", line 150, in split_dataset
    if is_train[os.path.splitext(file_name)[0]]:
KeyError: 'B001'
    if is_train[os.path.splitext(file_name)[0]]:
KeyError: 'B001'
[2024-10-02 08:58:30,694] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 60284) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main_rice3k.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-02_08:58:30
  host      : 64ccdd38f67e
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 60285)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-02_08:58:30
  host      : 64ccdd38f67e
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 60284)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

Could you please assist me in resolving this issue? I appreciate your help!

Thank you very much.

Best regards,
Louis

**Comment by RenqiChen** [comment]
Do you change the paths in `configs/rice3k.pth.json`?

**Comment by louislee711** [comment]
Yes, I have already changed the paths to match my setup.
But in your "rice3k.pth.json", it didn't have the args "fam_path"

here is my "rice3k.pth.json"
{
    "data_root": "/mnt/data/GS/Rice3k/Genotype/Seqs",
    "xlsx_path": "/mnt/data/GS/Rice3k/3kRG_PhenotypeData_v20170411.xlsx",
    "task_name": "PTH",
    "name2id_path": "/mnt/data/GS/Rice3k/3K_list_sra_ids.txt",
    "fold_root": "/mnt/data/GS/Rice3k/folds/pth",
    "vocabs": ["A","C","G","T","X"],
    "input_dim": 404388,
    "label_unique": true,
    "class_num": 3
}

Additionally, I downloaded the Rice3K dataset from the Google Drive link you provided.

**Comment by RenqiChen** [comment]
Hello, I ensure that "fam_path" is not needed. "xlsx_path" connects the ID (such as B001) with the Name, where the ID is to search for the genotype data (in the TXT file), and the Name is used to find the phenotype data (in the XLSX file).

**Comment by RenqiChen** [comment]
After re-checking your first error, from my perspective, I think you could first set normalize as `False`, and then run the code. Actually, I noticed the error appears in the log file, which is confusing.

**Comment by louislee711** [comment]
I have solved the first and second problem, but I still have another problem about hardware.
Thank for you help.

**Comment by RenqiChen** [comment]
Hello, we have revised some errors in the dataset_rice3k_45.py. We hope this can help you to reproduce our results.
